services:
  mysql:
    image: 'mysql:8.0' # latest보다는 버전을 명시하는 것이 안전합니다.
    container_name: my-website
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql